using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TaskTracker.Api.Tasks;
[ApiController]
[Route("api/tasks")]
[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
[Authorize]
[ProducesResponseType(StatusCodes.Status401Unauthorized)]
public sealed class TasksController(TaskService service) : ControllerBase
{
    
    // GET /api/tasks: return a filtered page of shared tasks for a signed-in user.
    [HttpGet]
    [EndpointSummary("List tasks")]
    [EndpointDescription("Requires sign-in. Returns shared tasks with createdByName plus totalCount, page, and pageSize. Creator names are null for older tasks without creator records. Page defaults to 1; pageSize defaults to 20 and must be 1-100. Optional status: Todo, InProgress, Done. Sorts by createdAt descending, then id ascending. Pages beyond the last return an empty items array.")]
    [ProducesResponseType(typeof(TaskPage), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public Task<TaskPage> List([FromQuery] TaskQuery query, CancellationToken cancellationToken) =>
        service.ListAsync(query, cancellationToken);

    // GET /api/tasks/{id}: return the full details of one task.
    [HttpGet("{id:guid}")]
    [EndpointSummary("Get a task")]
    [EndpointDescription("Requires sign-in. Returns the full task by its UUID, including description, status, priority, due date, UTC timestamps, and createdByName. A missing task or malformed UUID returns 404.")]
    [ProducesResponseType(typeof(TaskResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<TaskResponse>> Get(Guid id, CancellationToken cancellationToken) =>
        await service.GetAsync(id, cancellationToken) is { } task ? Ok(task) : NotFound();

    // POST /api/tasks: create a task and record the signed-in user as its creator.
    [HttpPost]
    [EndpointSummary("Create a task")]
    [EndpointDescription("Requires sign-in and a valid antiforgery token from GET /api/auth/me in the X-XSRF-TOKEN header. Title is trimmed and must contain 1-150 characters. Description allows up to 2000 characters. Status defaults to Todo; priority defaults to Medium. Due date is optional and may be in the past. Returns the created task and a Location header. ID and UTC timestamps are generated by the server. Creator identity comes from the signed-in session, not the request body. Returns 201 on success and 400 for invalid input or an invalid antiforgery token.")]
    [ProducesResponseType(typeof(TaskResponse), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<TaskResponse>> Create(SaveTaskRequest request, CancellationToken cancellationToken)
    {
        // Read the creator from the verified sign-in session, never from the request body.
        var creatorId = User.FindFirstValue("sub") ?? User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrWhiteSpace(creatorId)) return Unauthorized();
        var creatorName = User.FindFirstValue("preferred_username") ?? User.Identity?.Name
            ?? User.FindFirstValue("name") ?? creatorId;
        var task = await service.CreateAsync(request, creatorId, creatorName, cancellationToken);
        return CreatedAtAction(nameof(Get), new { id = task.Id }, task);
    }

    // PUT /api/tasks/{id}: replace editable fields while keeping the original creator.
    [HttpPut("{id:guid}")]
    [EndpointSummary("Update a task")]
    [EndpointDescription("Requires sign-in and a valid X-XSRF-TOKEN header. Replaces all editable fields using the same validation as creation. Omitted description and dueDate become null; omitted status and priority reset to Todo and Medium. Preserves id, createdAt, and the original creator; refreshes updatedAt. Returns the updated task, 400 for invalid input or an invalid antiforgery token, and 404 if the task is missing. Updates use last-write-wins; a concurrent deletion can return 409.")]
    [ProducesResponseType(typeof(TaskResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<TaskResponse>> Update(Guid id, SaveTaskRequest request, CancellationToken cancellationToken) =>
        await service.UpdateAsync(id, request, cancellationToken) is { } task ? Ok(task) : NotFound();

    // DELETE /api/tasks/{id}: permanently remove the task.
    [HttpDelete("{id:guid}")]
    [EndpointSummary("Delete a task")]
    [EndpointDescription("Requires sign-in and a valid X-XSRF-TOKEN header. Permanently deletes a shared task. An invalid or missing antiforgery token returns 400. Returns 204 with no body. Deleting an already deleted or missing task returns 404.")]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete(Guid id, CancellationToken cancellationToken) =>
        await service.DeleteAsync(id, cancellationToken) ? NoContent() : NotFound();
}


